runtime: nodejs10
env: standard
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
env_variables:
  DEV_SITE: "false"
  HUB_DEMO_ENABLED: "true"
  EMAIL_ADMIN_ENABLED: "false"
