version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "appvia-website"
      - GOOGLE_PROJECT_ID: 601743990716
      - GOOGLE_COMPUTE_ZONE: europe-west2-a
    steps:
      - checkout
      - run:
          comand: |
            apt-get install -qq -y gettext
            gcloud components install beta
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud beta auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud beta --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud beta --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          command: gcloud beta -q app deploy

workflows:
  version: 2
  run_release:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

