version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: |
            npm install
            npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy_test:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "appvia-hosting"
      - GOOGLE_PROJECT_ID: "appvia-hosting"
      - GOOGLE_COMPUTE_ZONE: "europe-west2-a"
      - LC_ALL: "C.UTF-8"
    steps:
      - checkout
      - run:
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            echo "  SF_USER: $DEV_SF_USER">>app-dev.yaml
            echo "  SF_TOKEN: $DEV_SF_TOKEN">>app-dev.yaml
            echo "  SF_PW: $DEV_SF_PW">>app-dev.yaml
            echo "  DEMO_REQUEST_GFORM_URL: $DEV_DEMO_REQUEST_GFORM_URL">>app-dev.yaml
            echo "  DEMO_FEEDBACK_GFORM_URL: $DEV_DEMO_FEEDBACK_GFORM_URL">>app-dev.yaml
            echo "  SLACK_DEMOS_URL: $DEV_SLACK_DEMOS_URL">>app-dev.yaml
            echo "  STORYBLOK_TOKEN: $DEV_STORYBLOK_TOKEN">>app-dev.yaml
      - run:
          command: gcloud -q app deploy app-dev.yaml dispatch.yaml
  deploy_main:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "appvia-hosting"
      - GOOGLE_PROJECT_ID: "appvia-hosting"
      - GOOGLE_COMPUTE_ZONE: "europe-west2-a"
    steps:
      - checkout
      - run:
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            echo "  SF_USER: $SF_USER">>app.yaml
            echo "  SF_TOKEN: $SF_TOKEN">>app.yaml
            echo "  SF_PW: $SF_PW">>app.yaml
            echo "  DEMO_REQUEST_GFORM_URL: $DEMO_REQUEST_GFORM_URL">>app.yaml
            echo "  DEMO_FEEDBACK_GFORM_URL: $DEMO_FEEDBACK_GFORM_URL">>app.yaml
            echo "  SLACK_DEMOS_URL: $SLACK_DEMOS_URL">>app.yaml
            echo "  STORYBLOK_TOKEN: $STORYBLOK_TOKEN">>app.yaml
      - run:
          command: gcloud -q app deploy

workflows:
  version: 2
  run_release:
    jobs:
      - build
      - deploy_test:
          filters:
            tags:
              only: /^test$/
            branches:
              only: /master/
      - deploy_main:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
